require:
  - rubocop-rspec

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/ContextWording:
  Enabled: false