inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword

# Place your custom cops configration here
